bloomberg/stricli

package-lock.json
package.json

We have decided to go with `nx release` instead.

chore: drop lerna dependency

---

packages/create-app/src/files.ts
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/with default flags.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/with default flags.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/with default flags.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/with default flags.txt

`@stricli/create-app` template creates a context with `NodeJS.Process` on it - so we add the type that.

fix(create-app): add process to context

---

.github/CODEOWNERS

Set the @bloomberg/stricli-devs team as the CODEOWNERS for all files in this repo

chore: define codeowners

---

docs/blog/2024-10-01-introducing-stricli.mdx

- Change publish date to today
- `npm i -P @stricli/core` instead of `-D`
- Switch link in blog that point to docs to be absolute with the domain
- See https://github.com/facebook/docusaurus/issues/9117

docs: final update of intro blog post

---

.prettierignore

`nx` is generating changelog updates that Prettier doesn't like. I think we can live without these updates, so ignoring the file

chore: prettierignore CHANGELOG.md

---

docs/docs/tutorial.mdx

Resolves #10 
This flag used to be called `--command-type` but it was renamed to `--template`. This section in the tutorial wasn't updated to match.

docs: correct typo with --template flag in tutorial

---

.github/CONTRIBUTING.md

I assumed this file was originally copied from https://github.com/bloomberg/.github
The LICENSE file was moved to the outer folder in this project, so I fixed the link accordingly.
I have also updated the `DCO.md` and `CODE_OF_CONDUCT.md` links to reference the organization-wide documents (they were not present in this repository). This ensures a single source of truth and helps avoid potential discrepancies.

docs: fix broken links in CONTRIBUTING.md

---

docs/docs/features/argument-parsing/flags.mdx
docs/docs/features/argument-parsing/index.mdx
docs/docs/features/configuration.mdx
docs/docusaurus.config.ts
docs/packages/index.mdx

*Issue number of the reported bug or feature request: #13*
It's said (and as I tested) that if GitHub Pages detects that the URL points to a directory on the server, it will add a trailing slash to the URL when refreshing.
<https://stackoverflow.com/a/33271505/2302258>
Per [Docusaurus's default configuration](https://docusaurus.io/docs/api/docusaurus-config#trailingSlash), `docs/getting-started/overview.mdx` would emit `docs/getting-started/overview/index.html`, therefore GitHub Pages would take `docs/getting-started/overview/` as the canonical URL.
However, the relative links in the document are not touched by default, so `./alternatives` remains `./alternatives`, which is `docs/getting-started/alternatives` on the original web page, and …

docs: set `trailingSlash: false` to fix refresh issues on GitHub pages

---

packages/create-app/src/files.ts
packages/create-app/src/impl.ts
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/with default flags.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/with default flags.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/with default flags.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/additional features/without auto-complete.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom metadata.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom name and bin command.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/package properties/custom name.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/with default flags.txt

Resolves #17 
Updates the autocomplete templates to iterate over the completions and print them to stdout (with a newline separator).
Generated sample app and tested/confirmed autocomplete functionality.
**Additional context**
While editing the files I also switched to 4-space in the template files so it would match our internal Prettier config.

fix: update auto-complete template to output completions

---

docs/docs/getting-started/alternatives.mdx

*Issue number of the reported bug or feature request: #15 
Added a short paragraph about yargs to the popular alternatives 
it compiles locally 
**Additional context**
congrats on the launch

Added yargs to list of popular alternatives in /docs

---

.github/workflows/pr_labels.yml
scripts/add_labels_to_pr.sh

Script to iterate over file names in diff between PR branch and main, and add a label for each of the packages affected.
~Will test live on this PR.~ Tested on this PR, `ci 🤖` label added correctly.

ci: script to add label to PR based on edited package

---

packages/core/src/index.ts
packages/core/src/parameter/types.ts

Resolves #22 
Export constituent types of TypedCommandParameters individually. Renamed `TypedCommandFlagParameters` and `TypedCommandPositionalParameters` before exporting so the correct user-facing type is used.
Changes are type-only, relying on CI tests

fix: export constituent types of TypedCommandParameters individually

---

packages/core/src/parameter/flag/types.ts
packages/core/tests/baselines/reference/parameter/flag/formatting.txt
packages/core/tests/baselines/reference/parameter/formatting.txt
packages/core/tests/parameter/flag/formatting.spec.ts
packages/core/tests/parameter/formatting.spec.ts
packages/core/tests/parameter/scanner.spec.ts

Resolves #21 
Prior to this change, any flag type that extended from `readonly (infer A)[]` would be interpreted as a `variadic` parameter. The variadic modifier allows the flag to be specified multiple times, each input parsed separately, and the results returned as an array. However, this did not allow for the use case that a single parsed value (i.e. `--flag=a,b,c`) could produce an array as output (`["a", "b", "c"]`).
With this change, the `variadic` modifier can be dropped from flags with an array-based type and the parser will then expect that exact array-based type as output.
Updated both formatting and scanner tests to confirm the new behavior.
**Additional context**
This also allows for the possibility of accepting specific …

fix: allow flags to parse arrays without variadic modifier

---

nx.json

Should not release `stricli-*-example` packages or `@stricli/docs` package (as they are not published). As well, use conventional commits to determine the next version.
Ran `nx release --dry-run`.

chore: remove docs/examples from release, use conventional commits

---

.github/workflows/release.yml

Required to publish npm provenance https://nx.dev/recipes/nx-release/publish-in-ci-cd#npm-provenance

ci: enable id-token permission for npm provenance

---

packages/create-app/src/app.ts
packages/create-app/src/impl.ts
packages/create-app/src/node.ts
packages/create-app/src/registry.ts
packages/create-app/tests/app.spec.ts
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/node version logic/exact version exists for types.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/node version logic/major version does not exist in registry, picks highest even major.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/node version logic/major version exists in registry.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/node version logic/version discovery skipped when --node-version is provided.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/NPM_EXECPATH throws an error.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/no check for safe major version.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/reads registry direct from NPM_CONFIG_REGISTRY, URL ends with slash.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/reads registry direct from NPM_CONFIG_REGISTRY.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/registry data has no versions.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/request to registry throws error.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/unable to discover registry from process.txt
packages/create-app/tests/baselines/reference/app/creates new application/checks for @types__node/registry logic/uses NPM_EXECPATH to get registry config value.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/additional features/without eslint and prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/additional features/without eslint.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/commonjs/additional features/without prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/additional features/without eslint and prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/additional features/without eslint.txt
packages/create-app/tests/baselines/reference/app/creates new application/multi-command/module [default]/additional features/without prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/additional features/without eslint and prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/additional features/without eslint.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/commonjs/additional features/without prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/additional features/without eslint and prettier.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/additional features/without eslint.txt
packages/create-app/tests/baselines/reference/app/creates new application/single-command/module [default]/additional features/without prettier.txt

Resolves #30 
New behavior to check the locally-configured registry for `@types/node` and only write a version that exists to the `package.json` for the new project.
The registry URL is pulled from one of two sources:
- The `NPM_CONFIG_REGISTRY` environment variable
- Less common use case, but good to read from an env var if possible
- Executes `NPM_EXECPATH` with `process.execPath` and args `config get registry`
- This method works for npm, yarn, and pnpm as all of them set that environment variable and share those command line args (tested this manually)
Once the data is fetched from the registry, there is additional logic to determine if there is an exact or approximate (same major version) version of `@types/node` available. If not it defaults to the highest …

fix: verify @types/node version with registry

---

docs/src/css/custom.scss

Button to expand/collapse the monaco portion of the live playground had an insufficient `z-index` value and was partially obscured by some monaco elements. Raised the `z-index` to 10 as that seemed to be sufficient.
Editor toggle button before:
Editor toggle button after:

docs: increase z-index of navbar to place on top of editor

---

docs/docs/features/argument-parsing/examples/array-argument.txt
docs/docs/features/argument-parsing/examples/boolean-flag.txt
docs/docs/features/argument-parsing/examples/bounded-array-argument.txt
docs/docs/features/argument-parsing/examples/counter-flag.txt
docs/docs/features/argument-parsing/examples/default-flag.txt
docs/docs/features/argument-parsing/examples/default-tuple-argument.txt
docs/docs/features/argument-parsing/examples/enum-flag.txt
docs/docs/features/argument-parsing/examples/hidden-flag.txt
docs/docs/features/argument-parsing/examples/optional-flag.txt
docs/docs/features/argument-parsing/examples/optional-tuple-argument.txt
docs/docs/features/argument-parsing/examples/parsed-flag.txt
docs/docs/features/argument-parsing/examples/tuple-argument.txt
docs/docs/features/argument-parsing/examples/variadic-flag.txt

This property is required, but the playground examples used an empty string. This results in less than optimal help text and is not the pattern that we want to recommend.
Tested against a local copy of the documentation site.

docs: populate brief for all live playground examples

---

docs/docs/features/argument-parsing/examples/boolean-flag.txt
docs/docs/features/command-routing/commands.mdx
packages/core/src/routing/command/documentation.ts
packages/core/tests/application.spec.ts
packages/core/tests/baselines/reference/application.txt
packages/core/tests/baselines/reference/routing/command.txt
packages/core/tests/routing/command.spec.ts

Resolves #20 
Change `customUsage` to accept either a `string` or `{ input: string; brief: string }` and include the `brief` on the line after the usage (indented).
Updated baselines with new output and added new test cases to ensure 100% coverage.
**Additional follow-up**
Currently the briefs are indented and formatted with _italics_, but I'm not sure if it makes sense to change up the formatting to make them more visible/readable.

feat: new option to display brief with custom usage

---

.github/workflows/release.yml

Release workflow needs git user to correctly commit/tag/push changes. As per [this thread](https://github.com/orgs/community/discussions/26560#discussioncomment-3531273), the user name and email were set for `github-actions[bot]`.

ci: set github-actions[bot] as git user for release

---

packages/core/src/parameter/scanner.ts
packages/core/tests/baselines/reference/parameter/flag/formatting.txt
packages/core/tests/parameter/flag/formatting.spec.ts

Loosens the regex used for flag pattern matching to allow:
- Periods
- Underscores
- Digits
...which enables flags like `--foo.bar`, `--foo123`, and `--foo_bar`.

fix: loosen character restrictions on flags

---

.github/workflows/pr_labels.yml

https://github.com/bloomberg/stricli/settings/actions
All workflows have read/write permissions for all scopes, so this shouldn't be necessary

chore: remove explicit permissions

---

package-lock.json
packages/core/src/context.ts
packages/core/src/index.ts
packages/core/tests/application.spec.ts
packages/core/tests/fakes/context.ts

Resolves #44 
swiches to setting `exitCode` rather than calling `exit()`, per the [node](https://nodejs.org/download/release/v18.20.0/docs/api/process.html#processexitcode) guidance:
> The reason this is problematic is because writes to process.stdout in Node.js are sometimes asynchronous and may occur over multiple ticks of the Node.js event loop. Calling process.exit(), however, forces the process to exit before those additional writes to stdout can be performed.
>
> Rather than calling process.exit() directly, the code should set the process.exitCode and allow the process to exit naturally by avoiding scheduling any additional work for the event loop

fix: use exit code

---

nx.json

Add `--signoff` to git commit args for release commit, so that all commits are signed off (for DCO).

chore: add --signoff to git commit args for release

---

.github/workflows/ci.yml
.github/workflows/pr_labels.yml

Both of these jobs were named 'main' which made it impossible to disambiguate them or require one of them on PR.

ci: use more accurate job names for actions

---

README.md
docs/blog/2024-10-01-introducing-stricli.mdx
docs/docs/features/shell-autocomplete.mdx
docs/docs/quick-start.mdx
docs/docusaurus.config.ts
docs/src/pages/index.tsx

Addresses some of the feedback from #51 
Refer to the new application guide as a "quick start" rather than a "tutorial".

docs(quick-start): rename tutorial to quick start

---

docs/src/css/custom.scss

This would have been a drive-by change in a larger PR, but figured I'd land it first as a quick-win.
Before
After

docs: enhance ANSI bold styling

---

packages/core/src/parameter/parser/boolean.ts
packages/core/tests/parameter/parsers/boolean.spec.ts
packages/core/tests/parameter/scanner.spec.ts

In preparation for #62, the loose boolean parser should accept all commonly-used values for boolean environment variables. This list isn't exhaustive, but matches Python's (now deprecated) `distutils.util.strtobool`. 
Updated the test cases to ensure complete coverage.

fix: make looseBooleanParser even more permissive

---

nx.json

Use `v{version}` instead of `release/{version}` for release tags. I've already gone through and created the `v{version}` tags for all of the existing (and pending) releases.

chore: simplify release tag pattern

---

.github/workflows/publish.yml

The step `actions/setup-node@v4` has logic to account for authentication, which wasn't being invoked (despite passing `NODE_AUTH_TOKEN` to the publish step).
This just worked to publish `1.1.2` manually: https://github.com/bloomberg/stricli/actions/runs/14112648127

ci: set registry-url and auth token in setup-node

---

docs/docs/features/argument-parsing/index.mdx

Resolves #77 
Add admonition in the argument parsing section that `strict: true` is strongly recommended for proper argument type checking.

docs: recommend strict for TypeScript compilation

---

docs/docs/features/argument-parsing/flags.mdx
packages/core/src/parameter/flag/formatting.ts
packages/core/src/parameter/flag/types.ts
packages/core/src/parameter/scanner.ts
packages/core/src/routing/command/builder.ts
packages/core/src/text.ts
packages/core/tests/baselines/reference/parameter/flag/formatting.txt
packages/core/tests/parameter/flag/formatting.spec.ts
packages/core/tests/parameter/scanner.spec.ts
packages/core/tests/routing/command.spec.ts

Resolves #74 
Allow `variadic` option for flags to be a string. If set, Stricli will use that string as a separator and call `.split(separator)` on every raw input (before it is parsed/validated).
For example, `variadic: ","` will split the raw input `--flag 1,2,3` into `["1", "2", "3"]` which will each be parsed separately (assuming this is a parsed number flag). This can still be combined with multiple instances of the same flag, so `--flag 1,2 --flag 3` will be `["1", "2", "3"]` as well.
Added several new test cases to achieve complete coverage.
**Additional context**
I've also added some additional validation to the flag specification, as the separator cannot be the empty string and should not include any whitespace.
**Note:** I don't …

feat: custom separators for variadic flags

---

packages/core/eslint.config.mjs
packages/core/tests/application.spec.ts
packages/core/tests/baselines/reference/parameter/flag/formatting.txt
packages/core/tests/baselines/reference/parameter/positional/formatting.txt
packages/core/tests/baselines/reference/routing/command.txt
packages/core/tests/baselines/reference/routing/route-map.txt
packages/core/tests/parameter/flag/formatting.spec.ts
packages/core/tests/parameter/positional/formatting.spec.ts
packages/core/tests/routing/command.spec.ts
packages/core/tests/routing/route-map.spec.ts

We have baseline tests for the formatting of certain outputs. These outputs can be formatted with or without ANSI colors/styling. Previously, the tests had to pick whether to turn ANSI colors on or off and then could only test that one setting. To test all cases, the test suite now invokes each formatting function twice, once with ANSI and once without ANSI. These are saved as two separate baselines (and also compared to each other, so that the version without ANSI is the same as the one with ANSI if all of the ANSI-specific characters are stripped out).
This also improves the readability of the baselines that were previously ANSI-only.
These are changes to the test suite only.

test: automatically run doc baselines with/without ANSI

---

packages/core/src/parameter/scanner.ts
packages/core/tests/parameter/scanner.spec.ts

[This change](https://github.com/bloomberg/stricli/commit/2088ffdc038b1676f7f1d6fdc3451b7a07ec10cc) to loosen the restrictions on flag names was only applied to the regex for `--flag=value` syntax and not the `--flag value` syntax.
Expanded test suite to account for flags with numeric characters.

fix: relax flag name pattern to allow alphanumeric (and more)

---

packages/core/src/index.ts
packages/core/src/parameter/positional/types.ts
packages/core/src/parameter/types.ts

These types can be useful when constructing commands piecemeal and there is a case to separately define `CommandModule` or one of the related types.

fix: expose additional types for command module
